debug(actions): further debug issue

diff --git a/.github/workflows/build-test-deploy.yml b/.github/workflows/build-test-deploy.yml
--- a/.github/workflows/build-test-deploy.yml
+++ b/.github/workflows/build-test-deploy.yml
@@ -64,8 +64,9 @@ jobs:
         if: steps.skip-ci.outputs.should-skip != 'true'
         id: data
         run: |
+          set -x
           NPMR=`npm run`
-          if [ -r ./release.config.js ]; then HAS_RCNF=true; else HAS_RCNF=false; fi
+          if [ -r release.config.js ]; then HAS_RCNF=true; else HAS_RCNF=false; fi
           echo $NPMR | grep -q build-docs
           if [ $? -eq 0 ]; then HAS_DOCS=true; else HAS_DOCS=false; fi
           echo $NPMR | grep -q build-externals
@@ -86,8 +87,8 @@ jobs:
           echo "::set-output name=has-integration-webpack::$HAS_WEBP"
           echo "::set-output name=has-integration-externals::$HAS_IEXT"
           if [ $HAS_EXTS != $HAS_IEXT ]; then
-            echo '::error::expected both 1) ./external-scripts directory to exist and 2) `test-integration-externals` run-script to be defined in package.json'
-            exit 2
+            echo '::error::expected both 1) `external-scripts` directory to exist and 2) `test-integration-externals` run-script to be defined in package.json'
+            exit 1
           fi
           if [ $HAS_DOCS = 'false' ]; then
             echo '::warning::no `build-documentation` run-script defined in package.json'
