build(.github/workflows/cleanup.yml): add metadata filtering step

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -9,11 +9,63 @@ on:
 env:
   NODE_CURRENT_VERSION: 15.x
   IGNORE_TAGS: 'latest' # example: IGNORE_TAGS: 'tag1, tag2, tag-3'
-  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+  # ! These also have to be updated in .changelogrc.js and cleanup.yml
+  CI_SKIP_COMMANDS: '[skip ci], [ci skip], [skip github], [github skip]'
+  # ? Add your GitHub user/org to enable this pipeline workflow
+  # ? (you'll need to provide your own secrets or the pipeline will error)
+  REPO_OWNER_WHITELIST: xunnamius, ergodark, nhscc
 
 jobs:
+  metadata:
+    name: 'gather-metadata'
+    runs-on: ubuntu-latest
+    outputs:
+      should-skip-ci: ${{ steps.skip-ci.outputs.should-skip == 'true' }}
+      has-proper-owner: ${{ steps.owner.outputs.is-whitelisted }}
+      has-release-config: ${{ steps.data.outputs.has-release-config == 'true' }}
+      has-package-json: ${{ steps.data.outputs.has-package-json == 'true' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1 # ! We only skip if the tippy top commit says so!
+
+      - name: Gather CI metadata
+        uses: mstachniuk/ci-skip@v1.2.0
+        with:
+          commit-filter: ${{ env.CI_SKIP_COMMANDS }}
+          commit-filter-separator: ', '
+
+      - name: Determine should-skip
+        id: skip-ci
+        run: echo "::set-output name=should-skip::$CI_SKIP"
+
+      - name: Verify repository owner against whitelist
+        if: steps.skip-ci.outputs.should-skip != 'true'
+        id: owner
+        run: |
+          set +e
+          WL='${{ env.REPO_OWNER_WHITELIST }}'
+          REPO='${{ github.repository }}'
+          node -e "process.exit('$WL'.toLowerCase().split(',').some(o => '$REPO'.toLowerCase().startsWith(o.trim() + '/')) ? 0 : 1)"
+          echo "::set-output name=is-whitelisted::$([ $? -eq 0 ] && echo 'true' || echo 'false')"
+
+      - name: Gather package.json script metadata
+        if: steps.skip-ci.outputs.should-skip != 'true'
+        id: data
+        run: |
+          set +e
+          [ -r release.config.js ] && echo "::set-output name=has-release-config::$HAS_RCNF"
+          [ -r package.json ] && echo "::set-output name=has-package-json::$HAS_RCNF"
+
   cleanup-npm-dist-tags:
     runs-on: ubuntu-latest
+    needs: metadata
+    if: |
+      needs.metadata.outputs.should-skip-ci != 'true'
+      && needs.metadata.outputs.has-proper-owner == 'true'
+      && needs.metadata.outputs.has-release-config == 'true'
+      && needs.metadata.outputs.has-package-json == 'true'
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -39,17 +91,15 @@ jobs:
           path: ~/.npm
 
       - name: Remove any erroneous dist tags
+        env:
+          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
         run: |
-          if [ -r "./release.config.js" ]; then
-            npm install micromatch
-            git remote prune origin
-            BRANCHES=`git for-each-ref --format='%(refname:lstrip=3)' refs/remotes/origin`
-            export BRANCHES
-            PKG_NAME=`node -e 'console.log(require("./package.json").name)'`
-            DIST_TAGS=`npm dist-tag list "$PKG_NAME"`
-            export DIST_TAGS
-            MATCHED_TAGS=$(node -e 'const match = require("micromatch"); const tags = process.env.DIST_TAGS.split("\n").map(t => t.split(":")[0]); const branches = match(process.env.BRANCHES.split("\n"), require("./release.config.js").branches.reduce((a,b) => [...a, b.name || b.toString()], [])); const ignoreTags = process.env.IGNORE_TAGS.split(", "); console.log(tags.reduce((a,t) => branches.some(b => ignoreTags.includes(t) || t == b || t == `release-${b}`) ? a : [...a, t], []).join(" ").trim())')
-            if ! [ -z "$MATCHED_TAGS" ]; then echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc; echo $MATCHED_TAGS | xargs -n1 npm dist-tag rm "$PKG_NAME"; else echo "dist tags OK!"; fi
-          else
-
-          fi
+          npm install micromatch
+          git remote prune origin
+          BRANCHES=`git for-each-ref --format='%(refname:lstrip=3)' refs/remotes/origin`
+          export BRANCHES
+          PKG_NAME=`node -e 'console.log(require("./package.json").name)'`
+          DIST_TAGS=`npm dist-tag list "$PKG_NAME"`
+          export DIST_TAGS
+          MATCHED_TAGS=$(node -e 'const match = require("micromatch"); const tags = process.env.DIST_TAGS.split("\n").map(t => t.split(":")[0]); const branches = match(process.env.BRANCHES.split("\n"), require("./release.config.js").branches.reduce((a,b) => [...a, b.name || b.toString()], [])); const ignoreTags = process.env.IGNORE_TAGS.split(", "); console.log(tags.reduce((a,t) => branches.some(b => ignoreTags.includes(t) || t == b || t == `release-${b}`) ? a : [...a, t], []).join(" ").trim())')
+          if ! [ -z "$MATCHED_TAGS" ]; then echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc; echo $MATCHED_TAGS | xargs -n1 npm dist-tag rm "$PKG_NAME"; else echo "dist tags OK!"; fi
